version: "3.8"

services:
  weather-frontend:
    build: ./frontend
    container_name: weather-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - weather-backend

  weather-backend:
    build: ./backend
    container_name: weather-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - weather-db

  weather-db:
    image: mongo
    container_name: weather-db
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
